"""
Frontend Career Data Generator
Converts database/seeds/careers.json + Decision Engine scoring
into strongly typed TypeScript data for frontend/src/data/mockAlignxData.ts.
"""

import os
import json
from backend.engine.models import CareerProfile, StudentProfileInput, FamilyProfileInput
from backend.engine.scoring_engine import AlignxDecisionEngine

def generate():
    root = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
    careers_path = os.path.join(root, "database", "seeds", "careers.json")
    with open(careers_path, "r", encoding="utf-8") as f:
        raw_careers = json.load(f)

    careers = [CareerProfile.model_validate(c) for c in raw_careers]
    raw_map = {c["id"]: c for c in raw_careers}

    student = StudentProfileInput(
        id="std_demo",
        name="Student",
        location="Bangalore",
        willingToRelocate=True
    )
    family = FamilyProfileInput(
        totalBudgetINR=1600000,
        loanWillingnessINR=600000,
        riskAppetite="medium"
    )

    engine = AlignxDecisionEngine()
    results = engine.rank_careers(student, family, careers)

    domain_names = {
        "ai_data": "AI Systems & Neural Computing",
        "cloud_devops": "Cloud & Distributed Systems",
        "cybersecurity": "Cybersecurity & Cryptography",
        "software_web": "Software Systems & Web Architecture",
        "robotics_embedded": "Robotics & Cyber-Physical Systems",
        "biotech_health": "Computational Biology & HealthTech",
        "aerospace": "Aerospace & Autonomous Flight",
        "clean_energy": "CleanTech & Energy Systems",
        "quantum": "Quantum Computing & Algorithms",
        "design_product": "UI/UX & Product Design",
        "spatial_ar_vr": "Spatial Computing & AR/VR",
        "iot_edge": "Edge Intelligence & IoT Networks"
    }

    ts_careers = []
    for r in results:
        raw_c = raw_map[r.career_id]
        c_prof = next(c for c in careers if c.id == r.career_id)

        # Risk level string
        risk_raw = c_prof.risk_level
        risk_str = "High" if risk_raw == "high" else ("Low" if risk_raw == "low" else "Moderate")

        growth_cagr = round(c_prof.market_data.growth_score * 0.32)
        sal_min = c_prof.salary_range.entry_lpa.min
        sal_max = c_prof.salary_range.senior_lpa.max
        salary_str = f"₹{sal_min:g}L — ₹{sal_max:g}L CTC"

        top_locs = [loc.location for loc in c_prof.location_demand]
        req_skills = [s.name for s in c_prof.skills]

        strengths = []
        apt_dict = c_prof.aptitude_profile.model_dump()
        for k, v in apt_dict.items():
            if v >= 85:
                strengths.append(f"High {k.capitalize()} Aptitude ({v:.0f}/100)")
        if not strengths:
            strengths = ["Balanced analytical aptitude", "Methodical problem-solving"]

        why_rec = [
            f"Strong alignment with {domain_names.get(c_prof.domain, c_prof.domain)} requirements.",
            f"Hiring velocity index of {c_prof.market_data.hiring_velocity}/100 across major tech hubs.",
            f"Entry compensation up to ₹{c_prof.salary_range.entry_lpa.max}L with accelerated 5-year growth."
        ]

        exams = [e.get("exam", "") for e in raw_c.get("entranceExams", []) if e.get("exam")]
        schols = [s.get("name", "") for s in raw_c.get("scholarships", []) if s.get("name")]
        edu_path = c_prof.education_pathway.degrees[0] if c_prof.education_pathway.degrees else "B.Tech"

        ts_careers.append({
            "id": r.career_id,
            "title": r.career_name,
            "domain": domain_names.get(r.domain, r.domain.replace("_", " ").title()),
            "tagline": c_prof.description,
            "scores": {
                "studentFit": round(r.component_scores.student_fit),
                "financialFit": round(r.component_scores.financial_fit),
                "familyAlignment": round(r.component_scores.family_alignment),
                "marketFit": round(r.component_scores.market_fit),
                "locationFit": round(r.component_scores.location_fit),
                "overallScore": round(r.alignx_score)
            },
            "growthRate": f"+{growth_cagr}% CAGR",
            "salaryRange": salary_str,
            "riskLevel": risk_str,
            "topLocations": top_locs,
            "requiredSkills": req_skills,
            "studentSkillGaps": r.skill_gaps if r.skill_gaps else ["Specialized cloud toolchains", "Domain-specific frameworks"],
            "strengthsMatch": strengths[:3],
            "whyRecommended": why_rec,
            "educationPath": edu_path,
            "entranceExams": exams[:3] if exams else ["JEE Mains / Advanced", "State CET"],
            "scholarships": schols[:3] if schols else ["National Scholarship Portal (NSP)", "Merit-cum-Means Scheme"]
        })

    ts_content = "// Generated by backend/scripts/generate_frontend_careers.py\n"
    ts_content += "import type { CareerRecommendation } from '../types/alignx';\n\n"
    ts_content += f"export const ALL_AUTHENTIC_CAREERS: CareerRecommendation[] = {json.dumps(ts_careers, indent=2)};\n"

    out_file = os.path.join(root, "frontend", "src", "data", "allCareers.ts")
    with open(out_file, "w", encoding="utf-8") as f:
        f.write(ts_content)

    return ts_careers

if __name__ == "__main__":
    careers = generate()
    print(f"Generated {len(careers)} typed career definitions to frontend/src/data/allCareers.ts")
