// Generated by backend/scripts/generate_frontend_careers.py
import type { CareerRecommendation } from '../types/alignx';

export const ALL_AUTHENTIC_CAREERS: CareerRecommendation[] = [
  {
    "id": "ai_ml_engineer",
    "title": "AI & Machine Learning Engineer",
    "domain": "AI Systems & Neural Computing",
    "tagline": "Designs, builds, and deploys scalable machine learning models, neural networks, and generative AI systems into production architectures.",
    "scores": {
      "studentFit": 88,
      "financialFit": 84,
      "familyAlignment": 86,
      "marketFit": 95,
      "locationFit": 92,
      "overallScore": 89
    },
    "growthRate": "+31% CAGR",
    "salaryRange": "₹9.5L — ₹80L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Delhi NCR",
      "Chennai"
    ],
    "requiredSkills": [
      "Python Programming",
      "Deep Learning & Neural Networks",
      "Machine Learning",
      "Data Structures & Algorithms",
      "Mathematical & Statistical Modeling"
    ],
    "studentSkillGaps": [
      "Python Programming",
      "Deep Learning & Neural Networks",
      "Machine Learning",
      "Data Structures & Algorithms",
      "Mathematical & Statistical Modeling"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (92/100)",
      "High Numerical Aptitude (88/100)",
      "High Analytical Aptitude (95/100)"
    ],
    "whyRecommended": [
      "Strong alignment with AI Systems & Neural Computing requirements.",
      "Hiring velocity index of 95.0/100 across major tech hubs.",
      "Entry compensation up to ₹16.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech Computer Science / AI / Data Science",
    "entranceExams": [
      "JEE Main / Advanced",
      "BITSAT",
      "VITEEE / MET"
    ],
    "scholarships": [
      "Central Sector Scheme of Scholarships",
      "Reliance Foundation Undergraduate Scholarship"
    ]
  },
  {
    "id": "vlsi_semiconductor_design_engineer",
    "title": "VLSI & Semiconductor Design Engineer",
    "domain": "Robotics Hardware",
    "tagline": "Designs microchips, ASIC architectures, FPGA synthesis blocks, and system-on-chips (SoC) for modern computing and India Semiconductor Mission.",
    "scores": {
      "studentFit": 85,
      "financialFit": 88,
      "familyAlignment": 89,
      "marketFit": 93,
      "locationFit": 89,
      "overallScore": 88
    },
    "growthRate": "+31% CAGR",
    "salaryRange": "₹9L — ₹75L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Noida / Delhi NCR",
      "Chennai",
      "Gujarat (Dholera / Sanand)"
    ],
    "requiredSkills": [
      "Embedded C / C++",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling"
    ],
    "studentSkillGaps": [
      "Embedded C / C++",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (94/100)",
      "High Numerical Aptitude (92/100)",
      "High Analytical Aptitude (96/100)"
    ],
    "whyRecommended": [
      "Strong alignment with robotics_hardware requirements.",
      "Hiring velocity index of 94.0/100 across major tech hubs.",
      "Entry compensation up to ₹16.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / M.Tech in Microelectronics / VLSI / ECE / Electrical Engineering",
    "entranceExams": [
      "JEE Advanced",
      "GATE (for M.Tech VLSI)"
    ],
    "scholarships": [
      "India Semiconductor Mission (ISM) Fellowship"
    ]
  },
  {
    "id": "data_platform_engineer",
    "title": "Data Platform & Cloud Engineer",
    "domain": "AI Systems & Neural Computing",
    "tagline": "Constructs high-throughput distributed data pipelines, lakehouses, and stream-processing infrastructure for enterprise analytics.",
    "scores": {
      "studentFit": 82,
      "financialFit": 89,
      "familyAlignment": 85,
      "marketFit": 89,
      "locationFit": 90,
      "overallScore": 86
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "₹8.5L — ₹65L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Chennai",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Big Data & Distributed Computing",
      "Python Programming",
      "Relational Databases & SQL",
      "Cloud Architecture (AWS/GCP/Azure)",
      "Document & Vector DBs (MongoDB/Pinecone)"
    ],
    "studentSkillGaps": [
      "Big Data & Distributed Computing",
      "Python Programming",
      "Relational Databases & SQL",
      "Cloud Architecture (AWS/GCP/Azure)",
      "Document & Vector DBs (MongoDB/Pinecone)"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (88/100)",
      "High Analytical Aptitude (90/100)"
    ],
    "whyRecommended": [
      "Strong alignment with AI Systems & Neural Computing requirements.",
      "Hiring velocity index of 91.0/100 across major tech hubs.",
      "Entry compensation up to ₹14.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech Computer Science / Information Technology / Data Engineering",
    "entranceExams": [
      "JEE Main",
      "State CET (MHT-CET / KCET / WBJEE)"
    ],
    "scholarships": [
      "Siemens Scholarship for Technical Students"
    ]
  },
  {
    "id": "cybersecurity_analyst",
    "title": "Cybersecurity & Cryptographic Analyst",
    "domain": "Software Cloud",
    "tagline": "Protects enterprise systems against cyber warfare, vulnerability exploits, and data breaches using zero-trust architecture and cryptographic protocols.",
    "scores": {
      "studentFit": 80,
      "financialFit": 92,
      "familyAlignment": 86,
      "marketFit": 88,
      "locationFit": 86,
      "overallScore": 84
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "₹7L — ₹52L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Delhi NCR",
      "Hyderabad",
      "Mumbai",
      "Pune"
    ],
    "requiredSkills": [
      "Network Security & Cryptography",
      "Python Programming",
      "AI Ethics & Data Privacy",
      "Cloud Architecture (AWS/GCP/Azure)"
    ],
    "studentSkillGaps": [
      "Network Security & Cryptography",
      "Python Programming",
      "AI Ethics & Data Privacy",
      "Cloud Architecture (AWS/GCP/Azure)"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (90/100)",
      "High Analytical Aptitude (94/100)"
    ],
    "whyRecommended": [
      "Strong alignment with software_cloud requirements.",
      "Hiring velocity index of 93.0/100 across major tech hubs.",
      "Entry compensation up to ₹12.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Cybersecurity / Computer Science / Information Security",
    "entranceExams": [
      "NFSU National Entrance Test",
      "JEE Main"
    ],
    "scholarships": [
      "National Scholarship for Cyber Forensics"
    ]
  },
  {
    "id": "technical_product_manager",
    "title": "Technical Product Manager (AI & STEAM)",
    "domain": "UI/UX & Product Design",
    "tagline": "Defines product vision, feature requirements, user conversion metrics, and cross-functional engineering execution for AI-first products.",
    "scores": {
      "studentFit": 78,
      "financialFit": 86,
      "familyAlignment": 81,
      "marketFit": 86,
      "locationFit": 88,
      "overallScore": 82
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b98L \u2014 \u20b975L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Delhi NCR (Gurugram)",
      "Mumbai",
      "Hyderabad",
      "Pune"
    ],
    "requiredSkills": [
      "Product Strategy & Metrics",
      "UI/UX & Design Systems",
      "Python Programming",
      "AI Ethics & Data Privacy"
    ],
    "studentSkillGaps": [
      "Product Strategy & Metrics",
      "UI/UX & Design Systems",
      "AI Ethics & Data Privacy"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (88/100)",
      "High Analytical Aptitude (92/100)",
      "High Verbal Aptitude (94/100)"
    ],
    "whyRecommended": [
      "Strong alignment with UI/UX & Product Design requirements.",
      "Hiring velocity index of 90.0/100 across major tech hubs.",
      "Entry compensation up to \u20b915.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Computer Science / Engineering + MBA / Product Fellowship",
    "entranceExams": [
      "JEE Main",
      "CAT (Post-Grad)"
    ],
    "scholarships": [
      "Aditya Birla Scholarship / Reliance Undergraduate"
    ]
  },
  {
    "id": "cloud_devops_architect",
    "title": "Cloud Systems & DevOps Architect",
    "domain": "Software Cloud",
    "tagline": "Architects resilient multi-cloud infrastructures, automated deployment pipelines, container orchestration, and site reliability systems.",
    "scores": {
      "studentFit": 45,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 80,
      "locationFit": 90,
      "overallScore": 76
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b97.5L \u2014 \u20b958L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Chennai",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Cloud Architecture (AWS/GCP/Azure)",
      "DevOps & CI/CD",
      "Python Programming",
      "Network Security & Cryptography"
    ],
    "studentSkillGaps": [
      "Cloud Architecture (AWS/GCP/Azure)",
      "DevOps & CI/CD",
      "Python Programming",
      "Network Security & Cryptography"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (86/100)",
      "High Analytical Aptitude (88/100)"
    ],
    "whyRecommended": [
      "Strong alignment with software_cloud requirements.",
      "Hiring velocity index of 89.0/100 across major tech hubs.",
      "Entry compensation up to \u20b912.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Computer Science / Cloud Computing / Information Technology",
    "entranceExams": [
      "JEE Main",
      "COMEDK UGET"
    ],
    "scholarships": [
      "AWS Certified Cloud Scholarship / AICTE PRAGATI"
    ]
  },
  {
    "id": "satellite_systems_engineer",
    "title": "Satellite Communications & Space Tech Engineer",
    "domain": "Clean Energy Aerospace",
    "tagline": "Engineers CubeSats, satellite constellation orbital mechanics, phased-array telemetry payloads, and ground control antennas.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 82,
      "locationFit": 92,
      "overallScore": 76
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b97.5L \u2014 \u20b960L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Thiruvananthapuram",
      "Ahmedabad"
    ],
    "requiredSkills": [
      "Aerodynamics & Propulsion Systems",
      "Embedded C / C++",
      "Mathematical & Statistical Modeling",
      "Circuit & PCB Design"
    ],
    "studentSkillGaps": [
      "Aerodynamics & Propulsion Systems",
      "Embedded C / C++",
      "Mathematical & Statistical Modeling",
      "Circuit & PCB Design"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (92/100)",
      "High Numerical Aptitude (94/100)",
      "High Analytical Aptitude (95/100)"
    ],
    "whyRecommended": [
      "Strong alignment with clean_energy_aerospace requirements.",
      "Hiring velocity index of 89.0/100 across major tech hubs.",
      "Entry compensation up to \u20b913.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / M.Tech in Avionics / Aerospace / Telecommunications / Space Physics",
    "entranceExams": [
      "JEE Advanced",
      "GATE ECE / Aerospace"
    ],
    "scholarships": [
      "IN-SPACe Space Innovator Grant"
    ]
  },
  {
    "id": "electric_vehicle_powertrain_engineer",
    "title": "Electric Vehicle & Battery Systems Engineer",
    "domain": "Clean Energy Aerospace",
    "tagline": "Develops EV traction motor controllers, high-voltage battery management systems (BMS), regenerative braking, and thermal runaway prevention.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 80,
      "locationFit": 88,
      "overallScore": 75
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b96.5L \u2014 \u20b952L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Pune",
      "Chennai",
      "Bangalore",
      "Delhi NCR (Gurugram/Manesar)",
      "Gujarat (Sanand/Mandal)"
    ],
    "requiredSkills": [
      "Renewable Power & Grid Integration",
      "Embedded C / C++",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling"
    ],
    "studentSkillGaps": [
      "Renewable Power & Grid Integration",
      "Embedded C / C++",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (88/100)",
      "High Numerical Aptitude (86/100)",
      "High Analytical Aptitude (90/100)"
    ],
    "whyRecommended": [
      "Strong alignment with clean_energy_aerospace requirements.",
      "Hiring velocity index of 91.0/100 across major tech hubs.",
      "Entry compensation up to \u20b911.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Automotive / Electrical / Mechanical / E-Mobility Engineering",
    "entranceExams": [
      "JEE Main / Advanced",
      "MHT-CET / TNEA"
    ],
    "scholarships": [
      "Tata Motors E-Mobility Scholarship"
    ]
  },
  {
    "id": "full_stack_software_engineer",
    "title": "Full-Stack Software Engineer",
    "domain": "Software Cloud",
    "tagline": "Architects end-to-end web and mobile applications, handling dynamic frontend interfaces, backend microservices, and databases.",
    "scores": {
      "studentFit": 45,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 77,
      "locationFit": 91,
      "overallScore": 75
    },
    "growthRate": "+28% CAGR",
    "salaryRange": "\u20b96.5L \u2014 \u20b950L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Chennai",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Python Programming",
      "Data Structures & Algorithms",
      "Relational Databases & SQL",
      "UI/UX & Design Systems"
    ],
    "studentSkillGaps": [
      "Python Programming",
      "Data Structures & Algorithms",
      "Relational Databases & SQL"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (86/100)",
      "High Analytical Aptitude (86/100)"
    ],
    "whyRecommended": [
      "Strong alignment with software_cloud requirements.",
      "Hiring velocity index of 86.0/100 across major tech hubs.",
      "Entry compensation up to \u20b912.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / B.E. in Computer Science / Information Science / Software Engineering",
    "entranceExams": [
      "JEE Main",
      "State Engineering CETs"
    ],
    "scholarships": [
      "AICTE Pragati Scholarship for Girls"
    ]
  },
  {
    "id": "ui_ux_product_designer",
    "title": "UI/UX & Cognitive Product Designer",
    "domain": "UI/UX & Product Design",
    "tagline": "Blends cognitive psychology, interaction design, visual hierarchy, and accessible design systems to create intuitive user interfaces.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 77,
      "locationFit": 92,
      "overallScore": 75
    },
    "growthRate": "+28% CAGR",
    "salaryRange": "\u20b96L \u2014 \u20b948L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Delhi NCR (Gurugram)",
      "Mumbai",
      "Pune",
      "Hyderabad"
    ],
    "requiredSkills": [
      "UI/UX & Design Systems",
      "Product Strategy & Metrics",
      "AI Ethics & Data Privacy"
    ],
    "studentSkillGaps": [
      "UI/UX & Design Systems",
      "Product Strategy & Metrics",
      "AI Ethics & Data Privacy"
    ],
    "strengthsMatch": [
      "High Spatial Aptitude (95/100)",
      "High Verbal Aptitude (85/100)"
    ],
    "whyRecommended": [
      "Strong alignment with UI/UX & Product Design requirements.",
      "Hiring velocity index of 87.0/100 across major tech hubs.",
      "Entry compensation up to \u20b911.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Des / M.Des in Interaction Design / Human-Computer Interaction (HCI) / Product Design",
    "entranceExams": [
      "UCEED",
      "NID DAT"
    ],
    "scholarships": [
      "NID Merit-cum-Means Financial Aid"
    ]
  },
  {
    "id": "aerospace_avionics_engineer",
    "title": "Aerospace & Avionics Systems Engineer",
    "domain": "Clean Energy Aerospace",
    "tagline": "Designs flight navigation software, telemetry transceivers, fly-by-wire controls, and aerodynamic airframes for aircraft and defense drones.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 78,
      "locationFit": 92,
      "overallScore": 75
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b97L \u2014 \u20b958L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Thiruvananthapuram",
      "Chennai",
      "Nagpur / Pune"
    ],
    "requiredSkills": [
      "Aerodynamics & Propulsion Systems",
      "Embedded C / C++",
      "Mathematical & Statistical Modeling"
    ],
    "studentSkillGaps": [
      "Aerodynamics & Propulsion Systems",
      "Embedded C / C++",
      "Mathematical & Statistical Modeling"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (92/100)",
      "High Numerical Aptitude (92/100)",
      "High Analytical Aptitude (94/100)"
    ],
    "whyRecommended": [
      "Strong alignment with clean_energy_aerospace requirements.",
      "Hiring velocity index of 86.0/100 across major tech hubs.",
      "Entry compensation up to \u20b912.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Aerospace / Aeronautical / Avionics Engineering",
    "entranceExams": [
      "JEE Advanced",
      "GATE Aerospace"
    ],
    "scholarships": [
      "DOS / ISRO Financial Assistanceship"
    ]
  },
  {
    "id": "embedded_iot_engineer",
    "title": "Embedded Systems & IoT Engineer",
    "domain": "Robotics Hardware",
    "tagline": "Programs resource-constrained microcontrollers, RTOS kernels, sensor telemetry networks, and edge-intelligence hardware.",
    "scores": {
      "studentFit": 45,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 76,
      "locationFit": 90,
      "overallScore": 75
    },
    "growthRate": "+28% CAGR",
    "salaryRange": "\u20b96L \u2014 \u20b945L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Bangalore",
      "Chennai",
      "Pune",
      "Hyderabad",
      "Delhi NCR (Noida)"
    ],
    "requiredSkills": [
      "Embedded C / C++",
      "Circuit & PCB Design",
      "IoT Architectures & Edge AI",
      "Python Programming"
    ],
    "studentSkillGaps": [
      "Embedded C / C++",
      "Circuit & PCB Design",
      "IoT Architectures & Edge AI",
      "Python Programming"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (88/100)",
      "High Analytical Aptitude (88/100)"
    ],
    "whyRecommended": [
      "Strong alignment with robotics_hardware requirements.",
      "Hiring velocity index of 87.0/100 across major tech hubs.",
      "Entry compensation up to \u20b910.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Electronics & Communication (ECE) / Electrical (EEE) / Embedded Systems",
    "entranceExams": [
      "JEE Main",
      "KCET / TNEA"
    ],
    "scholarships": [
      "IESA Semiconductor Talent Scholarship"
    ]
  },
  {
    "id": "agritech_iot_engineer",
    "title": "Agritech & Smart Farming Systems Engineer",
    "domain": "Robotics Hardware",
    "tagline": "Engineers soil telemetry sensor grids, autonomous precision irrigation controllers, drone crop-health multispectral imaging, and agri-supply chain IoT.",
    "scores": {
      "studentFit": 45,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 77,
      "locationFit": 87,
      "overallScore": 75
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b95.5L \u2014 \u20b942L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Punjab (Ludhiana / Chandigarh)",
      "Maharashtra (Pune / Nashik)",
      "Tamil Nadu (Coimbatore)",
      "Bangalore",
      "Andhra Pradesh (Guntur/Vijayawada)"
    ],
    "requiredSkills": [
      "IoT Architectures & Edge AI",
      "Embedded C / C++",
      "Machine Learning",
      "Circuit & PCB Design"
    ],
    "studentSkillGaps": [
      "IoT Architectures & Edge AI",
      "Embedded C / C++",
      "Machine Learning",
      "Circuit & PCB Design"
    ],
    "strengthsMatch": [
      "High Analytical Aptitude (86/100)",
      "High Spatial Aptitude (88/100)"
    ],
    "whyRecommended": [
      "Strong alignment with robotics_hardware requirements.",
      "Hiring velocity index of 88.0/100 across major tech hubs.",
      "Entry compensation up to \u20b99.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Agricultural Engineering / IoT / Electronics & Communication",
    "entranceExams": [
      "ICAR AIEEA",
      "JEE Main"
    ],
    "scholarships": [
      "ICAR National Talent Scholarship (NTS)"
    ]
  },
  {
    "id": "renewable_energy_systems_engineer",
    "title": "Renewable Energy & Smart Grid Engineer",
    "domain": "Clean Energy Aerospace",
    "tagline": "Designs solar photovoltaic architectures, wind energy converters, battery energy storage systems (BESS), and green hydrogen power grids.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 80,
      "locationFit": 84,
      "overallScore": 75
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b96L \u2014 \u20b948L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Gujarat (Ahmedabad / Kutch)",
      "Rajasthan (Jaipur / Jodhpur)",
      "Tamil Nadu (Coimbatore / Chennai)",
      "Bangalore",
      "Maharashtra (Pune / Mumbai)"
    ],
    "requiredSkills": [
      "Renewable Power & Grid Integration",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling",
      "IoT Architectures & Edge AI"
    ],
    "studentSkillGaps": [
      "Renewable Power & Grid Integration",
      "Circuit & PCB Design",
      "Mathematical & Statistical Modeling",
      "IoT Architectures & Edge AI"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (86/100)",
      "High Numerical Aptitude (88/100)",
      "High Analytical Aptitude (90/100)"
    ],
    "whyRecommended": [
      "Strong alignment with clean_energy_aerospace requirements.",
      "Hiring velocity index of 90.0/100 across major tech hubs.",
      "Entry compensation up to \u20b910.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Energy Engineering / Electrical Engineering / Sustainable Technology",
    "entranceExams": [
      "JEE Main",
      "State CETs"
    ],
    "scholarships": [
      "National Renewable Energy Fellowship (MNRE)"
    ]
  },
  {
    "id": "robotics_systems_engineer",
    "title": "Robotics & Autonomous Systems Engineer",
    "domain": "Robotics Hardware",
    "tagline": "Integrates mechanical kinematics, embedded microcontrollers, computer vision, and ROS control algorithms to build intelligent robots.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 79,
      "locationFit": 87,
      "overallScore": 75
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b96.5L \u2014 \u20b952L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Pune",
      "Chennai",
      "Bangalore",
      "Delhi NCR (Gurugram/Faridabad)",
      "Hyderabad"
    ],
    "requiredSkills": [
      "Robotics Kinematics & Control",
      "Embedded C / C++",
      "Deep Learning & Neural Networks",
      "Circuit & PCB Design"
    ],
    "studentSkillGaps": [
      "Robotics Kinematics & Control",
      "Embedded C / C++",
      "Deep Learning & Neural Networks",
      "Circuit & PCB Design"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (90/100)",
      "High Numerical Aptitude (88/100)",
      "High Analytical Aptitude (92/100)"
    ],
    "whyRecommended": [
      "Strong alignment with robotics_hardware requirements.",
      "Hiring velocity index of 88.0/100 across major tech hubs.",
      "Entry compensation up to \u20b911.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Robotics & Mechatronics / Mechanical / Electrical / Electronics",
    "entranceExams": [
      "JEE Main / Advanced",
      "BITSAT"
    ],
    "scholarships": [
      "Kishore Vaigyanik / INSPIRE Fellowship"
    ]
  },
  {
    "id": "ar_vr_spatial_computing_engineer",
    "title": "AR/VR & Spatial Computing Engineer",
    "domain": "UI/UX & Product Design",
    "tagline": "Constructs immersive virtual realities, spatial audio pipelines, WebXR digital twins, and real-time 3D simulation engines.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 76,
      "locationFit": 90,
      "overallScore": 75
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b96.5L \u2014 \u20b952L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Pune",
      "Mumbai",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Spatial Computing & 3D Engines",
      "Data Structures & Algorithms",
      "UI/UX & Design Systems",
      "Python Programming"
    ],
    "studentSkillGaps": [
      "Spatial Computing & 3D Engines",
      "Data Structures & Algorithms",
      "UI/UX & Design Systems",
      "Python Programming"
    ],
    "strengthsMatch": [
      "High Spatial Aptitude (98/100)"
    ],
    "whyRecommended": [
      "Strong alignment with UI/UX & Product Design requirements.",
      "Hiring velocity index of 84.0/100 across major tech hubs.",
      "Entry compensation up to \u20b911.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Computer Science / Game Development / Spatial Computing / Digital Media",
    "entranceExams": [
      "UCEED / CEED",
      "JEE Main"
    ],
    "scholarships": [
      "AVGC National Center of Excellence Scholarship"
    ]
  },
  {
    "id": "fintech_quantitative_analyst",
    "title": "Fintech Quantitative & Algorithmic Analyst",
    "domain": "AI Systems & Neural Computing",
    "tagline": "Constructs high-frequency algorithmic trading strategies, risk variance models, automated market-making algorithms, and quantitative portfolio optimization.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 80,
      "marketFit": 92,
      "locationFit": 89,
      "overallScore": 74
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b912L \u2014 \u20b9120L CTC",
    "riskLevel": "High",
    "topLocations": [
      "Mumbai",
      "Bangalore",
      "Delhi NCR (Gurugram)",
      "Hyderabad",
      "Gujarat (GIFT City Gandhinagar)"
    ],
    "requiredSkills": [
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Data Structures & Algorithms",
      "Machine Learning"
    ],
    "studentSkillGaps": [
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Data Structures & Algorithms",
      "Machine Learning"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (96/100)",
      "High Numerical Aptitude (98/100)",
      "High Analytical Aptitude (98/100)"
    ],
    "whyRecommended": [
      "Strong alignment with AI Systems & Neural Computing requirements.",
      "Hiring velocity index of 92.0/100 across major tech hubs.",
      "Entry compensation up to \u20b924.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Computer Science / Mathematics & Computing / Statistics / Financial Engineering",
    "entranceExams": [
      "JEE Advanced",
      "ISI Admission Test"
    ],
    "scholarships": [
      "Indian Statistical Institute Full Fellowship"
    ]
  },
  {
    "id": "climate_tech_environmental_engineer",
    "title": "Climate Tech & Carbon Systems Engineer",
    "domain": "Clean Energy Aerospace",
    "tagline": "Constructs carbon capture simulations, urban climate adaptation models, environmental telemetry networks, and industrial effluent recycling plants.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 77,
      "locationFit": 87,
      "overallScore": 74
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b95.5L \u2014 \u20b944L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Delhi NCR",
      "Bangalore",
      "Mumbai",
      "Chennai",
      "Gujarat (Surat/Vapi)"
    ],
    "requiredSkills": [
      "Renewable Power & Grid Integration",
      "Computational Biology & Biostatistics",
      "Mathematical & Statistical Modeling",
      "AI Ethics & Data Privacy"
    ],
    "studentSkillGaps": [
      "Renewable Power & Grid Integration",
      "Computational Biology & Biostatistics",
      "Mathematical & Statistical Modeling",
      "AI Ethics & Data Privacy"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (86/100)",
      "High Analytical Aptitude (90/100)"
    ],
    "whyRecommended": [
      "Strong alignment with clean_energy_aerospace requirements.",
      "Hiring velocity index of 87.0/100 across major tech hubs.",
      "Entry compensation up to \u20b99.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Environmental Engineering / Chemical Engineering / Climate Sciences",
    "entranceExams": [
      "JEE Main",
      "GATE Environmental Science"
    ],
    "scholarships": [
      "MoEFCC Green Skill Development Scholarship"
    ]
  },
  {
    "id": "bioinformatics_scientist",
    "title": "Bioinformatics & Genomic Data Scientist",
    "domain": "Computational Biology & HealthTech",
    "tagline": "Applies statistical algorithms, computational biology, and machine learning to decode DNA/RNA sequencing data and discover new therapeutics.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 76,
      "locationFit": 89,
      "overallScore": 74
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b96L \u2014 \u20b948L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Hyderabad",
      "Bangalore",
      "Pune",
      "Chennai",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Genomic Data Analysis & NGS",
      "Computational Biology & Biostatistics",
      "Python Programming",
      "Machine Learning"
    ],
    "studentSkillGaps": [
      "Genomic Data Analysis & NGS",
      "Computational Biology & Biostatistics",
      "Python Programming",
      "Machine Learning"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (92/100)",
      "High Numerical Aptitude (88/100)",
      "High Analytical Aptitude (95/100)"
    ],
    "whyRecommended": [
      "Strong alignment with Computational Biology & HealthTech requirements.",
      "Hiring velocity index of 86.0/100 across major tech hubs.",
      "Entry compensation up to \u20b910.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / M.Sc in Bioinformatics / Biotechnology / Computational Biology",
    "entranceExams": [
      "IISER IAT / NEST",
      "CUET UG / JEE Main"
    ],
    "scholarships": [
      "DBT Junior Research Fellowship / INSPIRE"
    ]
  },
  {
    "id": "nanotechnology_materials_scientist",
    "title": "Nanotechnology & Advanced Materials Scientist",
    "domain": "Robotics Hardware",
    "tagline": "Synthesizes 2D graphene nanomaterials, metamaterials, carbon nanotubes, and nano-composites for next-generation solar cells, chips, and aerospace.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 75,
      "locationFit": 92,
      "overallScore": 74
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b96L \u2014 \u20b952L CTC",
    "riskLevel": "Moderate",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Chennai",
      "Pune",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Mathematical & Statistical Modeling",
      "Circuit & PCB Design",
      "Renewable Power & Grid Integration"
    ],
    "studentSkillGaps": [
      "Mathematical & Statistical Modeling",
      "Circuit & PCB Design",
      "Renewable Power & Grid Integration"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (90/100)",
      "High Numerical Aptitude (90/100)",
      "High Analytical Aptitude (95/100)"
    ],
    "whyRecommended": [
      "Strong alignment with robotics_hardware requirements.",
      "Hiring velocity index of 83.0/100 across major tech hubs.",
      "Entry compensation up to \u20b910.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / BS in Nanotechnology / Materials Science / Metallurgical Engineering",
    "entranceExams": [
      "JEE Advanced",
      "IISER IAT"
    ],
    "scholarships": [
      "Nano Mission India Fellowship"
    ]
  },
  {
    "id": "biomedical_device_engineer",
    "title": "Biomedical & MedTech Device Engineer",
    "domain": "Computational Biology & HealthTech",
    "tagline": "Engineers medical diagnostics, wearable health monitors, MRI/ultrasound signal processors, and FDA/CDSCO compliant healthcare devices.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 75,
      "locationFit": 88,
      "overallScore": 74
    },
    "growthRate": "+29% CAGR",
    "salaryRange": "\u20b95.5L \u2014 \u20b942L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Andhra Pradesh (Visakhapatnam - AMTZ)",
      "Bangalore",
      "Chennai",
      "Hyderabad",
      "Delhi NCR"
    ],
    "requiredSkills": [
      "Biomedical Instrumentation & Sensors",
      "Circuit & PCB Design",
      "Embedded C / C++",
      "IoT Architectures & Edge AI"
    ],
    "studentSkillGaps": [
      "Biomedical Instrumentation & Sensors",
      "Circuit & PCB Design",
      "Embedded C / C++",
      "IoT Architectures & Edge AI"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (86/100)",
      "High Analytical Aptitude (88/100)",
      "High Spatial Aptitude (88/100)"
    ],
    "whyRecommended": [
      "Strong alignment with Computational Biology & HealthTech requirements.",
      "Hiring velocity index of 85.0/100 across major tech hubs.",
      "Entry compensation up to \u20b99.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Biomedical Engineering / Medical Electronics / Instrumentation",
    "entranceExams": [
      "JEE Main",
      "TNEA / MET"
    ],
    "scholarships": [
      "National Health Mission Technical Scholarship"
    ]
  },
  {
    "id": "computational_biologist",
    "title": "Computational Biologist & Drug Discovery Specialist",
    "domain": "Computational Biology & HealthTech",
    "tagline": "Uses molecular dynamics simulations, structural biology models, and generative chemistry to accelerate drug discovery pipelines.",
    "scores": {
      "studentFit": 43,
      "financialFit": 100,
      "familyAlignment": 100,
      "marketFit": 75,
      "locationFit": 88,
      "overallScore": 74
    },
    "growthRate": "+28% CAGR",
    "salaryRange": "\u20b96.5L \u2014 \u20b950L CTC",
    "riskLevel": "Low",
    "topLocations": [
      "Hyderabad",
      "Bangalore",
      "Mumbai",
      "Pune",
      "Ahmedabad"
    ],
    "requiredSkills": [
      "Computational Biology & Biostatistics",
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Machine Learning"
    ],
    "studentSkillGaps": [
      "Computational Biology & Biostatistics",
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Machine Learning"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (90/100)",
      "High Numerical Aptitude (90/100)",
      "High Analytical Aptitude (94/100)"
    ],
    "whyRecommended": [
      "Strong alignment with Computational Biology & HealthTech requirements.",
      "Hiring velocity index of 84.0/100 across major tech hubs.",
      "Entry compensation up to \u20b910.5L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / BS in Computational Biology / Biotechnology / Pharmacy",
    "entranceExams": [
      "IISER IAT",
      "GPAT / CUET"
    ],
    "scholarships": [
      "CSIR Innovation Fellowship"
    ]
  },
  {
    "id": "quantum_software_researcher",
    "title": "Quantum Computing & Algorithms Researcher",
    "domain": "AI Systems & Neural Computing",
    "tagline": "Develops quantum error correction, variational quantum eigensolvers (VQE), and quantum cryptographic circuits on superconducting and photonic qubits.",
    "scores": {
      "studentFit": 42,
      "financialFit": 100,
      "familyAlignment": 80,
      "marketFit": 85,
      "locationFit": 92,
      "overallScore": 73
    },
    "growthRate": "+31% CAGR",
    "salaryRange": "\u20b910L \u2014 \u20b990L CTC",
    "riskLevel": "High",
    "topLocations": [
      "Bangalore",
      "Pune",
      "Chennai",
      "Delhi NCR",
      "Hyderabad"
    ],
    "requiredSkills": [
      "Quantum Mechanics & Algorithms",
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Data Structures & Algorithms"
    ],
    "studentSkillGaps": [
      "Quantum Mechanics & Algorithms",
      "Mathematical & Statistical Modeling",
      "Python Programming",
      "Data Structures & Algorithms"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (98/100)",
      "High Numerical Aptitude (98/100)",
      "High Analytical Aptitude (98/100)"
    ],
    "whyRecommended": [
      "Strong alignment with AI Systems & Neural Computing requirements.",
      "Hiring velocity index of 82.0/100 across major tech hubs.",
      "Entry compensation up to \u20b918.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech / BS in Physics / Computer Science / Mathematics $\\rightarrow$ MS/Ph.D. in Quantum Computing",
    "entranceExams": [
      "IISER IAT / KVPY",
      "JEE Advanced"
    ],
    "scholarships": [
      "National Quantum Mission (NQM) Doctoral Fellowship"
    ]
  },
  {
    "id": "blockchain_cryptographic_architect",
    "title": "Blockchain & Cryptographic Architect",
    "domain": "Software Cloud",
    "tagline": "Designs zero-knowledge proofs, smart contract security protocols, decentralized finance (DeFi) engines, and verifiable digital identity ledgers.",
    "scores": {
      "studentFit": 44,
      "financialFit": 100,
      "familyAlignment": 80,
      "marketFit": 76,
      "locationFit": 91,
      "overallScore": 72
    },
    "growthRate": "+28% CAGR",
    "salaryRange": "\u20b98L \u2014 \u20b980L CTC",
    "riskLevel": "High",
    "topLocations": [
      "Bangalore",
      "Delhi NCR (Gurugram)",
      "Hyderabad",
      "Mumbai",
      "Goa / Remote"
    ],
    "requiredSkills": [
      "Network Security & Cryptography",
      "Data Structures & Algorithms",
      "Python Programming",
      "Big Data & Distributed Computing"
    ],
    "studentSkillGaps": [
      "Network Security & Cryptography",
      "Data Structures & Algorithms",
      "Python Programming",
      "Big Data & Distributed Computing"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (94/100)",
      "High Numerical Aptitude (92/100)",
      "High Analytical Aptitude (96/100)"
    ],
    "whyRecommended": [
      "Strong alignment with software_cloud requirements.",
      "Hiring velocity index of 80.0/100 across major tech hubs.",
      "Entry compensation up to \u20b915.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Computer Science / Information Technology / Cryptography",
    "entranceExams": [
      "JEE Main"
    ],
    "scholarships": [
      "Ethereum Foundation / Web3 India Scholar Grant"
    ]
  },
  {
    "id": "computational_neuroscience_researcher",
    "title": "Computational Neuroscience & BCI Specialist",
    "domain": "Computational Biology & HealthTech",
    "tagline": "Models brain neural dynamics, neural signal decoding algorithms, brain-computer interfaces (BCI), and neuromorphic computing circuits.",
    "scores": {
      "studentFit": 42,
      "financialFit": 100,
      "familyAlignment": 80,
      "marketFit": 77,
      "locationFit": 92,
      "overallScore": 71
    },
    "growthRate": "+30% CAGR",
    "salaryRange": "\u20b97L \u2014 \u20b965L CTC",
    "riskLevel": "High",
    "topLocations": [
      "Bangalore",
      "Hyderabad",
      "Delhi NCR (Gurugram)",
      "Chennai",
      "Pune"
    ],
    "requiredSkills": [
      "Deep Learning & Neural Networks",
      "Biomedical Instrumentation & Sensors",
      "Mathematical & Statistical Modeling",
      "Python Programming"
    ],
    "studentSkillGaps": [
      "Deep Learning & Neural Networks",
      "Biomedical Instrumentation & Sensors",
      "Mathematical & Statistical Modeling",
      "Python Programming"
    ],
    "strengthsMatch": [
      "High Logical Aptitude (95/100)",
      "High Numerical Aptitude (92/100)",
      "High Analytical Aptitude (96/100)"
    ],
    "whyRecommended": [
      "Strong alignment with Computational Biology & HealthTech requirements.",
      "Hiring velocity index of 80.0/100 across major tech hubs.",
      "Entry compensation up to \u20b912.0L with accelerated 5-year growth."
    ],
    "educationPath": "B.Tech in Biomedical / Electrical / CS $\\rightarrow$ MS/Ph.D. in Neuroscience / Cognitive Science",
    "entranceExams": [
      "IISER IAT / NEST",
      "GATE / JGEEBILS"
    ],
    "scholarships": [
      "DBT Cognitive Science Research Initiative (CSRI)"
    ]
  }
];
